Add .aab installation support
DeviceFarmer/stf pull request #103
Opened 2020-09-15 03:46 UTC by nghiaviminh

Drag & drop installation and launching of .aab files. Set your own keystore options to sign APKs in storage-temp unit

2020-09-20 14:23 UTC, koral-- requested changes

2020-09-20 14:23 UTC, koral-- commented on lib/util/bundletool.js
> +    var bundletoolUrl = 'https://api.github.com/repos/google/bundletool/releases/latest'
IMO bundletool should be bundled with docker image.
STF may be deployed in various environments which may not have network access.

2020-09-28 08:43 UTC, koral-- approved these changes
LGTM, but your branch is outdated.
Could you merge/rebase on latest changes?

2020-09-28 08:49 UTC, nghiaviminh commented
Of course, I'll update this branch on latest changes

2020-09-28 09:22 UTC, nghiaviminh commented
I've rebased the branch, you can merge changes.

2020-09-28 09:29 UTC, merged